version: '3'

services:
  api:
    container_name: "users-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: postgres_db
      DB_PORT: 5432

  db:
    container_name: users_postgres_db
    image: postgres:12
    ports:
          - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db

  ##keycloakdb:
    ##  container_name: db_keycloak
    ##  image: postgres:12
        ##ports:
    ##  - 5433:5432
      ##environment:
      ##POSTGRES_USER: sa
      ##POSTGRES_PASSWORD: password
      ##POSTGRES_DB: keycloak-db

    ##keycloak:
    ##image: quay.io/keycloak/keycloak:legacy
      ##environment:
      ##DB_VENDOR: POSTGRES
      ##DB_ADDR: db_keycloak
      ##DB_DATABASE: keycloak-db
      ##DB_USER: sa
      ##DB_SCHEMA: public
      ##DB_PASSWORD: password
      ##KEYCLOAK_USER: admin
      ##KEYCLOAK_PASSWORD: password
        ##ports:
      ##- 8080:8080
        ##depends_on:
      ##- keycloakdb